### ISSUE TITLE
Block region drag and drop broken

### ISSUE THREAD

**Issue by emmarichardson** [gjb2048/moodle-theme_foundation#15]
Hope I don't drive you crazy.  Having issues with the block regions.  With editing on, I see headings on the front page for the block regions but cannot seem to move blocks anywhere except to another position in the right side region and the drag and drop is totally disabled.

**Comment by gjb2048** [comment]
@emmarichardson Crazy = no = drag and drop of block regions appears to be broken, clicking on double headed arrow brings up pop-up with blocks to move current block underneath.  Will investigate.

**Comment by emmarichardson** [comment]
Glad to hear - also, if you select the region in the block settings, it also will NOT move it.  I have been unable to get any block in a different region.  So, could be that the additional block regions are also broken.

**Comment by gjb2048** [comment]
@emmarichardson I can move a block via it's settings, i.e. the 'On this page' section of the settings.

**Comment by gjb2048** [comment]
@emmarichardson I think I've fixed it and the above patch will solve the problem.  Thanks for reporting the issue.

**Comment by emmarichardson** [comment]
Confirmed as now working on my site.  Thanks Gareth.

**Comment by emmarichardson** [comment]
I am still unable to access the drawer region but all others work as expected.

**Comment by emmarichardson** [comment]
Update, just can't drag to Drawer region but block settings do work to add block there.

**Comment by gjb2048** [comment]
@emmarichardson Interesting, as I can drag to the Drawer region.  Is it open and showing it's name?

**Comment by emmarichardson** [comment]
Ok, I think it was a positioning issue. Once I had moved a block there by settings, I could drag over there too.  Then I took both blocks back out and found that I had to drag clear to the top, pretty much off the top of the page to get it to pick it up.  I am realizing now that the region names are actually the drag point?  And because the word "Drawer" is at that the very top you have to keep dragging up until part of the block is hidden by the navbar etc.  I will close this one out too!

**Comment by gjb2048** [comment]
@emmarichardson Ah, names are sort of a drag point, but not, please try the following custom CSS and see if that makes a difference:

```
.editing aside {
    height: 100%;
}
```

and may not now reply until tomorrow, as late here.

**Comment by emmarichardson** [comment]
That made it a lot better.  Thanks!

**Comment by gjb2048** [comment]
@emmarichardson This should now do the trick: https://github.com/gjb2048/moodle-theme_foundation/commit/b32019fc26be92b2756afc39586dfc50efbe278d.
